site_name: golist
theme:
  name: material
  logo: assets/golist-500.png
  icon:
    repo: fontawesome/brands/github

repo_name: a-poor/golist
repo_url: https://github.com/a-poor/golist
site_author: Austin Poor

nav:
  - Home: index.md
  - Installation: install.md
  - Features:
    - features/getting-started.md
  - Examples: []
  - "Issue Tracker": "https://github.com/a-poor/golist/issues"


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

